name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *' # har din midnight UTC par chalega
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate contribution snake graph
        uses: platane/snk@v0.4.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push snake graph
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution snake graph"
          git push
